version: '3'

## docker-compose up
## docker rm $(docker ps -a -q) && docker volume prune -f

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
     MYSQL_ROOT_PASSWORD: "love"
     MYSQL_DATABASE: golang
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'

  mongodb:
    image: 'mongo:5'
    environment:
      - MONGO_INITDB_DATABASE=coursera
    ports:
      - '27017:27017'