// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteResultInterface is an autogenerated mock type for the DeleteResultInterface type
type DeleteResultInterface struct {
	mock.Mock
}

type mockConstructorTestingTNewDeleteResultInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteResultInterface creates a new instance of DeleteResultInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteResultInterface(t mockConstructorTestingTNewDeleteResultInterface) *DeleteResultInterface {
	mock := &DeleteResultInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
