// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InsertOneResultInterface is an autogenerated mock type for the InsertOneResultInterface type
type InsertOneResultInterface struct {
	mock.Mock
}

type mockConstructorTestingTNewInsertOneResultInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewInsertOneResultInterface creates a new instance of InsertOneResultInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInsertOneResultInterface(t mockConstructorTestingTNewInsertOneResultInterface) *InsertOneResultInterface {
	mock := &InsertOneResultInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
