// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UpdateResultInterface is an autogenerated mock type for the UpdateResultInterface type
type UpdateResultInterface struct {
	mock.Mock
}

type mockConstructorTestingTNewUpdateResultInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateResultInterface creates a new instance of UpdateResultInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateResultInterface(t mockConstructorTestingTNewUpdateResultInterface) *UpdateResultInterface {
	mock := &UpdateResultInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
